name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format code with black
        run: |
          black .

      - name: Lint code with flake8
        run: |
          flake8 .

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report -m

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          upload_token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build and deploy to Heroku
        uses: heroku/deploy-v2@v1
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: your-heroku-app-name
          username: your-heroku-username

      - name: Rollback on failure
        if: failure()
        run: |
          heroku rollback -a your-heroku-app-name