name: Weather API CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          python -m unittest discover -s tests

      - name: Deploy to Google Cloud App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Notify on failure
        if: failure()
        uses: actions/send-slack-notification@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
          message: "Weather API CI/CD pipeline failed"

      - name: Notify on success
        if: success()
        uses: actions/send-slack-notification@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
          message: "Weather API CI/CD pipeline succeeded"